### ISSUE TITLE
please tag a release for abl_link

### ISSUE THREAD

**Issue by umlaeute** [libpd/abl_link#17]
once it's ready for link-3.0

**Comment by nettoyeurny** [comment]
Done: https://github.com/libpd/abl_link/releases/tag/link_3_0

**Comment by umlaeute** [comment]
thanks.
are the release going to be consistently `link_<majorversion>_<minorversion>`? (I'd like to use the tags to watch for new upstream releases, similar to [how I do it](https://qa.debian.org/cgi-bin/watch?pkg=ableton-link) for *Link* itself... (a scheme like `v<major>.<minor>` seems to be more popular...; however, i can live with  `link_<major>_<minor>` as well)

also, the `git describe` snippet in the [Makefile:44](https://github.com/libpd/abl_link/blob/d72e0112c6ea5f76e6a78bb877b814437c13c382/external/Makefile#L44) currently fails (afaik the `git tag`s need a message attached to them, in order to be picked up by `git describe` to produce a result), thus creating `deken` packages without any version string.

**Comment by umlaeute** [comment]
@nettoyeurny a related question: could you please clarify whether the actual version of *abl_link* really is `3.0`? (it seems to be obvious that this is version of Link itself; maybe you intend to follow their versions closely).

if i've tracked the older versions correctly, the last "release" was `0.2` (packaged in Debian) resp `0.3` (found on deken).

**Comment by nettoyeurny** [comment]
Interesting! I didn't do the packaging; not sure where the older version numbers came from.

The tag I assigned was supposed to indicate that this is for Link 3.0. If we're doing semantic versioning here, then the tag should be v0.4, I suppose. Would you like me to do that (with a message to address the git describe issue)?

**Comment by nettoyeurny** [comment]
Also, I'd be happy to equip you with the necessary privileges to make the changes you need. Please let me know if that works for you.

**Comment by umlaeute** [comment]
`v0.4` sounds like a good idea :-)

I have to admit that i myself don't have any idea (anymore) where the version numbers come from. (at least for the Debian package they would fall under my responsibility. i *guess* that i just followed the lead of the deken packages, but i don't really know).

regarding the privileges to do it myself: if you prefer this, it's fine with me, although the task is really quite minimal:

~~~
$ git tag v0.4 -m "Released abl_link v0.4"
$ git push --tags
~~~

**Comment by Ant1r** [comment]
Sorry I think i'm the one who assigned these numbers to the deken packages; not sure there was an actual logic though... IIRC the first working version had no version number yet (since it hadn't been uploaded to deken), then the second one was numbered v0.2, and the last one was v0.3.
I did tag my own fork with tag "0.3" (see https://github.com/Ant1r/abl_link/tree/0.3), then I realized that there was no way to PR the new tag to the libpd repo...

**Comment by nettoyeurny** [comment]
@umlaeute Why not both? :) I added the tag you suggested and I invited you to become a collaborator.

@Ant1r No need for apologies --- I really appreciate your help distributing this external!
