### ISSUE TITLE
Sample app: Gradle Sync failed

### ISSUE THREAD

**Issue by jbloit** [libpd/abl_link#18]
Hi,

I'm trying to run the sample app in Android Studio 3.0.1.  I followed the instructions, but I'm getting this error when the project is syncing with gradle files: 

`Gradle sync failed: Could not find method implementation() for arguments [com.noisepages.nettoyeur:midi:1.0.0-rc1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

Does it look familiar to you, do you see something obvious I can try to fix this?

Thank you

**Comment by cerupcat** [comment]
@jbloit Did you resolve this issue? I'm having the same issue.
