### ISSUE TITLE
drop shared library?

### ISSUE THREAD

**Issue by umlaeute** [libpd/abl_link#2]
any specifc reason to use a shared-library for the `abl_link_instance.cpp` instead of just statically linking it into the object?

this could simplify the [Makefile](https://github.com/libpd/abl_link/blob/master/external/Makefile#L15-L17) to:

    abl_link~.class.sources = abl_link~.cpp  abl_link_instance.cpp

**Comment by nettoyeurny** [comment]
Well, at an earlier stage we kicked around the idea of having two Link externals, one for musical purposes and one administrative one, and those were supposed to share one instance of Link. Since we've dropped this idea, I'll just go ahead and get rid of the separate library for abl_link_instance.
