### ISSUE TITLE
please tag a release for abl_link

### ISSUE THREAD

**Issue by umlaeute** [libpd/abl_link#23]
as mentioned in #22 , in order to get newer functionality like the `offset` message people start switching from the Debian/Ubuntu package to a self-compiled version of git.

by itself this is not a problem, but - with my Debian maintainer hat on - i'd like the Debian packages to be "what people expect".

@nettoyeurny please tag a new release, to ease my packaging workflow

**Comment by danomatika** [comment]
I’d suggest someone/anyone with access start a change of and tagging.  I’m not sure how much time Peter is able to put back into this external after the initial work he did.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by tkirshboim** [comment]
@umlaeute there are no new commits on the master branch since the [latest tag](https://github.com/libpd/abl_link/releases/tag/v0.4). Isn't the existing tag sufficient?

**Comment by umlaeute** [comment]
:facepalm:

this was triggered by #22, where the user claimed that:
> The Ubuntu `pd-ableton-link` package contains an older version that does not support the "offset" message.

i trusted them, that they were using a recent version of Ubuntu (`disco` comes with `pd-abletob-link==0.4`), and admit that i didn't check to thorougly.

sorry for the noise

**Comment by nettoyeurny** [comment]
Sorry about the tardy reply, @umlaeute ! I just merged a pull request that makes the offset message official, and I created a new release with a shiny new tag for you to package, v0.5 :)

**Comment by danomatika** [comment]
Thanks @nettoyeurny. I guess I spoke too soon.

**Comment by nettoyeurny** [comment]
Actually, you were quite right, @danomatika. I don't have much time to work on this these days. It just happened that there was a pull request that took care of the task at hand. Generally speaking, it would be great if someone else were to maintain this external.
