### ISSUE TITLE
abl_link~ does not appear in deken on raspbian 

### ISSUE THREAD

**Issue by CarloCattano** [libpd/abl_link#24]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

Pd-0.49.0 ("") compiled for Debian (0.49.0-3) on 2019/01/29 at 11:09:07 UTC

**Comment by Ant1r** [comment]
Actually I failed to compile for rPi when I tried last time 3 years ago (see #15).
Since then I'm using Carabiner on the pi... Next time I'll have a chance I'll give another try!

**Comment by CarloCattano** [comment]
Hey I succesfully comiled it in the pi no issues . I was just wondering cause in the past I remember to have installed it from decken directly from the pi at some point in the past.
Thanks for the good work !

**Comment by CarloCattano** [comment]
> 
> 
> well, yes. that's because nobody compiled `abl_link~` for arm and uploaded it to deken (the other binaries have been uploaded by @Ant1r at a best-effort basis).
> 
> anyhow, since you are using a Debian based distribution you could simply do:
> 
> ```
> apt-get install pd-ableton-link
> ```
> 
> (in theory, installing the `pd-deken-apt` package should allow you to install system ("Debian") packages via the "Find externals..." menu in Pd. however, it seems to be not working for `abl_link~` here, which you could consider a bug in `pd-deken-apt`)

True that , didnt think on reporting there , will do !
