### ISSUE TITLE
abl_link~ does not appear in deken (Windows - Pd version 0.51.3 64bit)

### ISSUE THREAD

**Issue by Knallberto** [libpd/abl_link#26]
I cannot find the ableton link external in PD. I am on a Windows 10 computer with PD 0.51.3 in 64 bit.

**Comment by danomatika** [comment]
@Lucarda feel like making a v0.6 build?

**Comment by Lucarda** [comment]
>@Lucarda feel like making a v0.6 build?

Did you mean a v3.0.1?

I can upload Windows and Linux versions.

**Comment by danomatika** [comment]
I'm adding a changelog to make sense of the version/release tags. I think the new version will be "v0.6" as it follows v0.4 and v0.6. I'll get back to you.

**Comment by Lucarda** [comment]
Oh, I see. I was confused by the last Deken version.

**Comment by danomatika** [comment]
Ok, basic changelog is there. The new tag with your Windows fixes is "v0.6", so I would use that in the deken naming.

**Comment by Lucarda** [comment]
Ok. I'll start new fresh builds just to check all is good with the merge.

**Comment by Lucarda** [comment]
The builds went fine and I uploaded them to Deken but they still don't show up.
I will investigate tomorrow as I have to sleep. :)

Just in case the builds are the two last at:

http://puredata.info/Members/lucarda/software/

**Comment by Lucarda** [comment]
@Knallberto 

You can find it on Deken now:

```
abl_link~[v0.6](Windows-amd64-32)(Windows-i386-32).dek
	Uploaded by lucarda @ 2021-05-26 00:21:59
```


:)
