### ISSUE TITLE
Successful Windows compilation.

### ISSUE THREAD

**Issue by Lucarda** [libpd/abl_link#27]
I could compile and run with the following tweaks:

1 - add this file https://github.com/Ableton/link/blob/master/include/ableton/platforms/windows/Windows.hpp to the sources.

2 - add these lines to `abl_link/external/link/include/ableton/discovery/NetworkByteStreamSerializable.hpp` line 27 :

```
#elif defined(LINK_PLATFORM_WINDOWS)
#include <ableton/platforms/windows/Windows.hpp>
```

3 - add this to the `makefile` on line 39 :

`ldlibs +=  -lws2_32 -liphlpapi`

Compiled with msys2(MINGW64) and run with Pd-0.51-4(amd64) and Ableton Live 10.1.14 on Windows-10.

May be steps 1 and 2 are unnecessary if updating `link @ 15024b4` to a newer one.

EDIT: I also updated pd-lib-builder to 0.6.0 (I got incompatible CPU errors with version 0.4.3).

**Comment by danomatika** [comment]
Can you make a PR with these changes?

**Comment by danomatika** [comment]
>May be steps 1 and 2 are unnecessary if updating link @ 15024b4 to a newer one.

You could also update the link submodule to a newer stable release tag.

**Comment by Lucarda** [comment]
Done with #28

**Comment by danomatika** [comment]
Mered #28.
